######################################################################
# Automatically generated by qmake (3.0) Tue Mar 18 08:41:30 2014
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
CONFIG += debug
CONFIG += c++17

LIBS += -lgtest -lpcosynchro

# Input
SOURCES += prodcons1.cpp

HEADERS += \
    abstractbuffer.h \
    buffer2conso.h
